export enum AuthErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
}

export enum ValidationErrorCode {
  REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING",
  INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT",
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
}

export enum ScheduleErrorCode {
  INVALID_TIME_ORDER = "INVALID_TIME_ORDER",
  OVERLAP = "OVERLAP",
  LIST_NOT_FOUND = "LIST_NOT_FOUND",
  CREATION_FAILED = "CREATION_FAILED",
  UPDATE_FAILED = "UPDATE_FAILED",
  DELETION_FAILED = "DELETION_FAILED",
  NOT_FOUND = "NOT_FOUND",
  SCHEDULE_INVALID_DATA = "SCHEDULE_INVALID_DATA",
  INVALID_RESPONSE = "INVALID_RESPONSE",
  UNAUTHORIZED = "UNAUTHORIZED",
}

export enum GeneralErrorCode {
  INVALID_INPUT = "INVALID_INPUT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export type ERROR_CODES = AuthErrorCode | ValidationErrorCode | ScheduleErrorCode | GeneralErrorCode;
